services:
  app:
    build: .
    container_name: mon-app
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules   # prevent overwriting node_modules with host’s empty folder
    command: sh -c "yarn dev --host 0.0.0.0 --port 5173"
    working_dir: /app
    stdin_open: true
    tty: true
